// <auto-generated />
using System;
using GasMonitor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GasMonitor.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124004002_AdicionaHistoricoTrocas")]
    partial class AdicionaHistoricoTrocas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GasMonitor.Api.Models.HistoricoTroca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataTroca")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoPago")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("HistoricoTrocas");
                });

            modelBuilder.Entity("GasMonitor.Api.Models.Medicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHoraRegisto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdDispositivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("VazamentoDetectado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Medicoes");
                });

            modelBuilder.Entity("GasMonitor.Api.Models.ProdutoConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<double>("CapacidadeTotalKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoPago")
                        .HasColumnType("numeric");

                    b.Property<double>("TaraKg")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoUnidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProdutosConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
